name: TeapartyPlugin
version: ${project.version}
main: ckcsc33rd.teapartyplugin.TeapartyPlugin
api-version: 1.15
authors: [ItisCaleb]
description: For CKCSC33rd Tea party
website: https://github.com/ItisCaleb
softdepend: [BungeeCord]
commands:

  teaparty:
    description: main
    aliases: teap
    usage: 完整指令列表請打 /teap help或是/teaparty help
  party:
    description: Custom teaming command
    aliases: p
    usage: 完整指令列表請打 /p help或是/party help
  lobby:
    description: lobby command
    aliases: l
    usage: /<command>
  adminteam:
    description: admin teaming command
    aliases: at
    usage: 完整指令列表請打 /at help或是/adminteam help
    permission: admin
    permission-message: "你不是管理員"
  club:
    description: club command
    aliases: cl
    usage: /<command> <create>
    permission: admin
    permission-message: "你不是管理員"
